import { Table, TableBody, TableCell, TableCellHead, TableFoot, TableHead, TableRow, TableRowHead } from '@dhis2/ui'
import React from 'react'

export default function Preview() {
  return (
    <div>
      <Table>
    <TableHead>
        <TableRowHead>
            <TableCellHead>
                Indicator Name
            </TableCellHead>
            <TableCellHead>
                Closing Balance (Stock on Hand)
            </TableCellHead>
            <TableCellHead>
                Losses
            </TableCellHead>
            <TableCellHead>
            (+ve) Adjustment
            </TableCellHead>
            <TableCellHead>
            (-ve) Adjustment
            </TableCellHead>
            <TableCellHead>
            Quantity Used in Period
            </TableCellHead>
            <TableCellHead>
            Stocked Out Days
            </TableCellHead>
            <TableCellHead>
            Quantity Received
            </TableCellHead>
        </TableRowHead>
    </TableHead>
    <TableBody>
    <TableRow>
            <TableCell>
            Acyclovir 200mg, tablets 
            </TableCell>
            <TableCell>
                {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
        </TableRow>
        <TableRow>
            <TableCell>
            Benzhexol 5mg
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
        </TableRow>
        <TableRow>
            <TableCell>
            Chlorpheniramine maleate 4mg
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
        </TableRow>
        <TableRow>
            <TableCell>
            Diclofenac sodium 50mg
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
        </TableRow>
        <TableRow>
            <TableCell>
            Erythromycin 250mg, enteric coated tablets
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
        </TableRow>
        <TableRow>
            <TableCell>
            Flucloxacillin 250mg, Capsules
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
        </TableRow>
        <TableRow>
            <TableCell>
            Griseofulvin 125mg, tablets
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
        </TableRow>
        <TableRow>
            <TableCell>
            Hydrochlorothiazide 25mg, tablets
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
        </TableRow>
        <TableRow>
            <TableCell>
            Indomethacin 25mg, Capsules
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
        </TableRow>
        <TableRow>
            <TableCell>
            Ketoconazole 200mg, tablets
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
            <TableCell>
            {Math.floor(Math.random()*(10000-100))}
            </TableCell>
        </TableRow>
        </TableBody>
    <TableFoot>
        <TableRow>
        </TableRow>
    </TableFoot>
</Table>
    </div>
  )
}
